meta_title: "60 Secs"
meta_product_name: "60 Secs - INSPIRE-SE - REINVENTE-SE "
meta_description: "De uma maneira rápida e fácil, encontramos seu estilo e otimizamos seu tempo na hora de se vestir para qualquer ocasião"
meta_image: "photo-meta-tag.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
